version: '2'

volumes:
  pg_data:
  gems:

services:
  db:
    image: postgres
    volumes:
    - pg_data:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
    ports:
    - 5433:5433
    - 5432:5432
    environment:
      POSTGRES_DB: mapper
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpw

  app:
    image: ruby
    ports:
    - 9000:9000
    links:
    - db
    volumes:
    - gems:/usr/local/bundle
    - .:/usr/src/app
    working_dir: /usr/src/app
    command: "sh -c 'bundle install && bundle exec rerun --background --dir lib --dir app -- bundle exec rackup --host 0.0.0.0 -p 9000'"
    environment:
      DATABASE_URL: postgres://user:userpw@db/mapper
    depends_on:
    - db

